-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglbtHpHDNzrvMWkKvdii6DfYTb8EOrOJ5Fif+FNeVTmugCgYIKoZIzj0DAQehRANCAAR3zdsIVfPPL4YfPe65FaRDVngXXf79hLzCiJ5N8+4NHCBv+NCU6UQWn7H4MP+b0PYjBNhIUHlvlQ3lGWMIdOhm
-----END PRIVATE KEY-----