-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1yp+YVP48hjoD8ZNjhUXyl13KJCEZvPsYxgoDhtNRHGgCgYIKoZIzj0DAQehRANCAATuRndaLPNKR6G3abd/icHYTd/KdkB7+kIc/rkekA3HIvBymN/u7B0Ded6I6ZnOQvZcrQvlHgyOHn+Q3lu1pjA7
-----END PRIVATE KEY-----