-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSlleXPOrXuhwn6AO9fVQ+tsF8PgQah4HHfQKFNgENkygCgYIKoZIzj0DAQehRANCAAR3qKnxwEOMY0nCyy0ZgetiJ9ulird+geYk12ZsJAAG7036V/PIwdEHDFr1xCbcdKxKs4KeEVOlnGwM9SzP8XaW
-----END PRIVATE KEY-----