-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFNoeCHKErcub0eIj/1hiwn1t6h5VcpY7QwN5m32D1YKgCgYIKoZIzj0DAQehRANCAAS2L/hyebedCS4STEu/j74tUHwbEjAQDkWlFyYKNNziWrAhRELeoLuNRt9RfpJD6+XE2w3SdVHHdolX9Zgof3nr
-----END PRIVATE KEY-----